/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proj.map.progettoMap1920.adventure.type;
import javax.swing.JPanel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.GroupLayout;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import java.awt.Color;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.border.TitledBorder;
import javax.swing.JButton;
import java.awt.Font;
import java.awt.Image;

import javax.swing.JLabel;

/**
 *
 * @author whyno
 */
public class DialogBox extends javax.swing.JFrame {

	/**
	 * Creates new form DialogBox
	 */
	public DialogBox() {
		getContentPane().setBackground(Color.LIGHT_GRAY);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(0, 0, 0));

		JScrollPane scrollPaneNpcDial = new JScrollPane();

		JScrollPane scrollPaneOpt1 = new JScrollPane();

		JScrollPane scrollPaneOpt2 = new JScrollPane();

		JScrollPane scrollPaneOpt3 = new JScrollPane();

		JScrollPane scrollPaneOpt4 = new JScrollPane();
		
		JLabel lblNewLabel = new JLabel(new ImageIcon(DialogBox.class.getResource("/img/download.jpg")));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.TRAILING)
				.addComponent(scrollPaneOpt1, GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
				.addComponent(scrollPaneOpt2, GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
				.addComponent(scrollPaneOpt3, GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
				.addComponent(scrollPaneOpt4, GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
				.addGroup(Alignment.LEADING, layout.createSequentialGroup()
					.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 204, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(scrollPaneNpcDial, GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(scrollPaneNpcDial, GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
						.addComponent(lblNewLabel, GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(scrollPaneOpt1, GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(scrollPaneOpt2, GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(scrollPaneOpt3, GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(scrollPaneOpt4, GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
					.addGap(31))
		);

		JButton btnOpt4 = new JButton("Opzione 4");
		scrollPaneOpt4.setRowHeaderView(btnOpt4);

		JTextArea textAreaOpt4 = new JTextArea();
		scrollPaneOpt4.setViewportView(textAreaOpt4);

		JButton btnOpt3 = new JButton("Opzione 3");
		scrollPaneOpt3.setRowHeaderView(btnOpt3);

		JTextArea textAreaOpt3 = new JTextArea();
		scrollPaneOpt3.setViewportView(textAreaOpt3);

		JButton btnOpt2 = new JButton("Opzione 2");
		scrollPaneOpt2.setRowHeaderView(btnOpt2);

		JTextArea textAreaOpt2 = new JTextArea();
		scrollPaneOpt2.setViewportView(textAreaOpt2);

		JButton btnOpt1 = new JButton("Opzione 1");
		scrollPaneOpt1.setRowHeaderView(btnOpt1);

		JTextArea textAreaOpt_1 = new JTextArea();
		scrollPaneOpt1.setViewportView(textAreaOpt_1);

		JTextArea npcText = new JTextArea();
		npcText.setFont(new Font("Eras Light ITC", Font.BOLD, 13));
		npcText.setBackground(Color.WHITE);
		npcText.setEditable(false);
		scrollPaneNpcDial.setViewportView(npcText);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DialogBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DialogBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DialogBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DialogBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new DialogBox().setVisible(true);
			}
		});
	}
}
