/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proj.map.progettoMap1920.adventure.type;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.GroupLayout;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import java.awt.Color;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JButton;
import java.awt.Font;

import javax.swing.JLabel;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JFrame;

/**
 *
 * @author whyno
 */
public class DialogBox extends javax.swing.JFrame {
	private static  Dialog d;
	/**
	 * Creates new form DialogBox
	 */
	public DialogBox(Dialog dialog) {
		getContentPane().setBackground(Color.LIGHT_GRAY);
		d = dialog;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(0, 0, 0));

		JScrollPane scrollPaneNpcDial = new JScrollPane();

		JScrollPane scrollPaneOpt1 = new JScrollPane();

		JScrollPane scrollPaneOpt2 = new JScrollPane();

		JScrollPane scrollPaneOpt3 = new JScrollPane();

		JLabel lblNewLabel = new JLabel(new ImageIcon(DialogBox.class.getResource("/img/download.jpg")));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 204, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(scrollPaneNpcDial, GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE))
				.addComponent(scrollPaneOpt1, GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
				.addComponent(scrollPaneOpt2, GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
				.addComponent(scrollPaneOpt3, GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(scrollPaneNpcDial, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
						.addComponent(lblNewLabel, GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(scrollPaneOpt1, GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(scrollPaneOpt2, GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
					.addGap(9)
					.addComponent(scrollPaneOpt3, GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
					.addContainerGap())
		);

		JButton btnOpt3 = new JButton("Opzione 3");
		scrollPaneOpt3.setRowHeaderView(btnOpt3);

		JTextArea textAreaOpt3 = new JTextArea();
		scrollPaneOpt3.setViewportView(textAreaOpt3);

		JButton btnOpt2 = new JButton("Opzione 2");
		scrollPaneOpt2.setRowHeaderView(btnOpt2);

		JTextArea textAreaOpt2 = new JTextArea();
		scrollPaneOpt2.setViewportView(textAreaOpt2);

		JButton btnOpt1 = new JButton("Opzione 1");




		scrollPaneOpt1.setRowHeaderView(btnOpt1);

		JTextArea textAreaOpt1 = new JTextArea();
		scrollPaneOpt1.setViewportView(textAreaOpt1);
		JTextArea npcText = new JTextArea();
		npcText.setFont(new Font("Eras Light ITC", Font.BOLD, 13));
		npcText.setBackground(Color.WHITE);
		npcText.setEditable(false);
		scrollPaneNpcDial.setViewportView(npcText);
		getContentPane().setLayout(layout);
		npcText.setText(d.getText());
		textAreaOpt1.setText(d.getOpt_1());
		textAreaOpt2.setText(d.getOpt_2());
		textAreaOpt3.setText(d.getOpt_3());
		


		btnOpt1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				try {
					if(d.getNext_1().getId()!= -1) {
						
						npcText.setText(d.getNext_1().getText());
						textAreaOpt1.setText(d.getNext_1().getOpt_1());
						textAreaOpt2.setText(d.getNext_1().getOpt_2());
						textAreaOpt3.setText(d.getNext_1().getOpt_3());
						


						try{
							setDialog(d.getNext_1());
							checkText(d,scrollPaneOpt1,scrollPaneOpt2,scrollPaneOpt3);
						}catch(NullPointerException n) {
							setVisible(false);
							dispose();
						}

					}else {
						setVisible(false);
						dispose();
					}
				} catch(NullPointerException n) {

				}
			}	
		});
		btnOpt2.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				try {
					if(d.getNext_2().getId()!= -1) {
						
						npcText.setText(d.getNext_2().getText());
						textAreaOpt1.setText(d.getNext_2().getOpt_1());
						textAreaOpt2.setText(d.getNext_2().getOpt_2());
						textAreaOpt3.setText(d.getNext_2().getOpt_3());
						

						try{
							setDialog(d.getNext_2());
							checkText(d,scrollPaneOpt1,scrollPaneOpt2,scrollPaneOpt3);
						}catch(NullPointerException n) {
							setVisible(false);
							dispose();
						}
					}else {
						setVisible(false);
						dispose();
					}
				}catch(NullPointerException n) {

				}	
			}
		});
		btnOpt3.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				try {
					if(d.getNext_3().getId()!= -1) {
						
						npcText.setText(d.getNext_3().getText());
						textAreaOpt1.setText(d.getNext_3().getOpt_1());
						textAreaOpt2.setText(d.getNext_3().getOpt_2());
						textAreaOpt3.setText(d.getNext_3().getOpt_3());	
						
						try{
							setDialog(d.getNext_3());
							checkText(d,scrollPaneOpt1,scrollPaneOpt2,scrollPaneOpt3);
							
						}catch(NullPointerException n) {
							setVisible(false);
							dispose();
						}
					}else {
						setVisible(false);
						dispose();
					}
				}catch(NullPointerException n) {

				}
			}
		});

		pack();
	}// </editor-fold>//GEN-END:initComponents


	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DialogBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DialogBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DialogBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DialogBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new DialogBox(d).setVisible(true);
			}
		});
	}
	public void setDialog(Dialog other) {
		d= other;
	}
	public void checkText(Dialog d, JScrollPane p1, JScrollPane p2, JScrollPane p3) {
		if(d.getOpt_1() == null) {
			p1.setVisible(false);
		}
		if(d.getOpt_2() == null) {
			p2.setVisible(false);
		}
		if(d.getOpt_3() == null) {
			p3.setVisible(false);
		}
	}

}
